### ISSUE TITLE
Unable to install the plugin on Ubuntu 20.04

### ISSUE THREAD

**Issue by eschoenawa** [BenSolus/linter-opencl#1]
I am unable to install the plugin on Ubuntu 20.04. See the attached error log:

```
> memwatch-next@0.2.10 install /tmp/apm-install-dir-2021525-16920-1dwejlj.ojia/node_modules/linter-opencl/node_modules/memwatch-next
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-2021525-16920-1dwejlj.ojia/node_modules/linter-opencl/node_modules/memwatch-next/build'
  CXX(target) Release/obj.target/memwatch/src/heapdiff.o
make: Leaving directory '/tmp/apm-install-dir-2021525-16920-1dwejlj.ojia/node_modules/linter-opencl/node_modules/memwatch-next/build'

npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably
npm WARN deprecated pngjs2@2.0.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:9116:75: warning: ‘v8::MicrotasksCompletedCallback’ is deprecated: Use *WithData version. [-Wdeprecated-declarations]
 9116 |   void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
      |                                                                           ^
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:7345:16: note: declared here
 7345 | typedef void (*MicrotasksCompletedCallback)(Isolate*);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:9124:78: warning: ‘v8::MicrotasksCompletedCallback’ is deprecated: Use *WithData version. [-Wdeprecated-declarations]
 9124 |   void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
      |                                                                              ^
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:7345:16: note: declared here
 7345 | typedef void (*MicrotasksCompletedCallback)(Isolate*);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/heapdiff.cc:12:
../src/heapdiff.hh:18:38: error: ‘v8::Handle’ has not been declared
   18 |         static void Initialize ( v8::Handle<v8::Object> target );
      |                                      ^~~~~~
../src/heapdiff.hh:18:44: error: expected ‘,’ or ‘...’ before ‘<’ token
   18 |         static void Initialize ( v8::Handle<v8::Object> target );
      |                                            ^
../src/heapdiff.cc:46:38: error: variable or field ‘Initialize’ declared void
   46 | heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
      |                                      ^~~~~~
../src/heapdiff.cc:46:38: error: ‘Handle’ is not a member of ‘v8’
../src/heapdiff.cc:46:55: error: expected primary-expression before ‘>’ token
   46 | heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
      |                                                       ^
../src/heapdiff.cc:46:57: error: ‘target’ was not declared in this scope
   46 | heapdiff::HeapDiff::Initialize ( v8::Handle<v8::Object> target )
      |                                                         ^~~~~~
../src/heapdiff.cc:93:33: error: ‘Handle’ does not name a type
   93 | static string handleToStr(const Handle<Value> & str)
      |                                 ^~~~~~
../src/heapdiff.cc:93:39: error: expected ‘,’ or ‘...’ before ‘<’ token
   93 | static string handleToStr(const Handle<Value> & str)
      |                                       ^
../src/heapdiff.cc: In function ‘std::string handleToStr(int)’:
../src/heapdiff.cc:95:30: error: ‘str’ was not declared in this scope; did you mean ‘std’?
   95 |  String::Utf8Value utfString(str->ToString());
      |                              ^~~
      |                              std
../src/heapdiff.cc: In function ‘void buildIDSet(std::set<long unsigned int>*, const v8::HeapGraphNode*, int&)’:
../src/heapdiff.cc:110:33: error: cannot convert ‘v8::Local<v8::String>’ to ‘int’
  110 |         handleToStr(cur->GetName()).compare("HeapDiff") == 0)
      |                     ~~~~~~~~~~~~^~
      |                                 |
      |                                 v8::Local<v8::String>
../src/heapdiff.cc:93:27: note:   initializing argument 1 of ‘std::string handleToStr(int)’
   93 | static string handleToStr(const Handle<Value> & str)
      |                           ^~~~~~~~~~~~
../src/heapdiff.cc: In function ‘void manageChange(changeset&, const v8::HeapGraphNode*, bool)’:
../src/heapdiff.cc:182:50: error: cannot convert ‘v8::Local<v8::String>’ to ‘int’
  182 |             type.append(handleToStr(node->GetName()));
      |                                     ~~~~~~~~~~~~~^~
      |                                                  |
      |                                                  v8::Local<v8::String>
../src/heapdiff.cc:93:27: note:   initializing argument 1 of ‘std::string handleToStr(int)’
   93 | static string handleToStr(const Handle<Value> & str)
      |                           ^~~~~~~~~~~~
../src/heapdiff.cc: At global scope:
../src/heapdiff.cc:223:8: error: ‘Handle’ does not name a type
  223 | static Handle<Value> changesetToObject(changeset & changes)
      |        ^~~~~~
../src/heapdiff.cc: In function ‘v8::Local<v8::Value> compare(const v8::HeapSnapshot*, const v8::HeapSnapshot*)’:
../src/heapdiff.cc:252:81: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
  252 |     b->Set(Nan::New("nodes").ToLocalChecked(), Nan::New(before->GetNodesCount()));
      |                                                                                 ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:254:50: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>&)’
  254 |     o->Set(Nan::New("before").ToLocalChecked(), b);
      |                                                  ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:257:80: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
  257 |     a->Set(Nan::New("nodes").ToLocalChecked(), Nan::New(after->GetNodesCount()));
      |                                                                                ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:259:49: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>&)’
  259 |     o->Set(Nan::New("after").ToLocalChecked(), a);
      |                                                 ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:265:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
  265 |     b->Set(Nan::New("size_bytes").ToLocalChecked(), Nan::New(s));
      |                                                                ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:266:102: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
  266 |     b->Set(Nan::New("size").ToLocalChecked(), Nan::New(mw_util::niceSize(s).c_str()).ToLocalChecked());
      |                                                                                                      ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:271:64: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
  271 |     a->Set(Nan::New("size_bytes").ToLocalChecked(), Nan::New(s));
      |                                                                ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:272:102: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
  272 |     a->Set(Nan::New("size").ToLocalChecked(), Nan::New(mw_util::niceSize(s).c_str()).ToLocalChecked());
      |                                                                                                      ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:277:72: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
  277 |     c->Set(Nan::New("size_bytes").ToLocalChecked(), Nan::New(diffBytes));
      |                                                                        ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:278:110: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>)’
  278 |     c->Set(Nan::New("size").ToLocalChecked(), Nan::New(mw_util::niceSize(diffBytes).c_str()).ToLocalChecked());
      |                                                                                                              ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:279:50: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Object>&)’
  279 |     o->Set(Nan::New("change").ToLocalChecked(), c);
      |                                                  ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:284:93: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
  284 |     c->Set(Nan::New("freed_nodes").ToLocalChecked(), Nan::New<v8::Number>(changedIDs.size()));
      |                                                                                             ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:300:97: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t)’
  300 |     c->Set(Nan::New("allocated_nodes").ToLocalChecked(), Nan::New<v8::Number>(changedIDs.size()));
      |                                                                                                 ^
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3664 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3664:37: note:   candidate expects 3 arguments, 2 provided
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3667 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:3667:37: note:   candidate expects 3 arguments, 2 provided
../src/heapdiff.cc:307:50: error: ‘changesetToObject’ was not declared in this scope
  307 |     c->Set(Nan::New("details").ToLocalChecked(), changesetToObject(changes));
      |                                                  ^~~~~~~~~~~~~~~~~
In file included from ../src/heapdiff.hh:8,
                 from ../src/heapdiff.cc:12:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/node_object_wrap.h:84:78:   required from here
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:10818:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10818 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/emil/.atom/.node-gyp/.cache/node-gyp/9.4.4/include/node/v8.h:10818:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [memwatch.target.mk:116: Release/obj.target/memwatch/src/heapdiff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.8.0-59-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2021525-16920-1dwejlj.ojia/node_modules/linter-opencl/node_modules/memwatch-next
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021525-16920-1dwejlj.ojia/package.json'
npm WARN apm-install-dir-2021525-16920-1dwejlj.ojia No description
npm WARN apm-install-dir-2021525-16920-1dwejlj.ojia No repository field.
npm WARN apm-install-dir-2021525-16920-1dwejlj.ojia No README data
npm WARN apm-install-dir-2021525-16920-1dwejlj.ojia No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memwatch-next@0.2.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memwatch-next@0.2.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/emil/.atom/.apm/_logs/2021-06-25T12_52_01_300Z-debug.log
```

**Comment by BenSolus** [comment]
memwatch-next is a dependency of node-opencl which this plugin uses to interact with the OpenCL-Runtime. Since node-opencl is pretty much abandoned I tried to replace it with node-opencl-ts, which seems to build on top of node-opencl and at least installs this package successful for me.
However, now something fails inside the plugin during program start of Atom which I don't understand yet. I look into it, but since I am not using OpenCL, Atom or this plugin actively anymore I can't promise anything.
